# Excluding not-stable configs

# group_imports = "StdExternalCrate"
hard_tabs = true
# imports_granularity = "Crate"
# match_block_trailing_comma = true
max_width = 88
newline_style = "Unix"
# reorder_impl_items = true
tab_spaces = 8
